channels:
  - conda-forge
  - bioconda
dependencies:
  - perl >=5.32.0
  - perl-file-spec
  - perl-findbin
  - spades >=3.14,<4
  - skesa >=2.5
  - megahit >=1.2.9
  - velvet >=1.2.10
  - lighter >=1.1
  - bwa >=0.7.17
  - kmc >=3.2
  - flash >=1.2
  - pilon >=1.22
  - samclip >=0.4
  - trimmomatic >=0.36
  - samtools >=1.10
  - seqkit
  - csvtk
