name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Pull code
        uses: actions/checkout@v5

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          miniforge-version: latest
          channels: conda-forge,bioconda
          channel-priority: strict
          activate-environment: shovill
          auto-update-conda: true

      - name: Set PATH
        run: |
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Basic tests
        run: |
          shovill --version
          shovill --check
          shovill --help
          ! shovill --doesnotexist

      - name: Prepare SHOVILL command
        run: |
          SHOVILL="shovill --cpus $(nproc) --R1 test/R1.fq.gz --R2 test/R2.fq.gz"

      - name: Test internal assemblers
        run: |
          for ASM in spades skesa megahit velvet ; do
            $SHOVILL --outdir $ASM --assembler $ASM --nocorr --noreadcorr --nostitch
            seqkit stats $ASM/contigs.fa
          done  

      - name: Test option combos on SKESA 
        run: |
          SHOVILL="$SHOVILL --assembler skesa"
          DIR=1
          for TRIM in '' '--trim' ; do
            for RCORR in '' '--noreadcorr' ; do
              for STITCH in '' '--nostitch' ; do 
                for ACORR in '' '--nocorr' ; do
                  $SHOVILL --outdir $DIR \
                    $TRIM $RCORR $STITCH $ACORR
                  seqkit stats $DIR/contigs.fa
                  ((DIR++))
                done
              done
            done
          done  
