name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Pull code
        uses: actions/checkout@v5

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
 #          python-version: 3.11
          miniforge-version: latest
          channels: conda-forge,bioconda
          channel-priority: strict
          activate-environment: shovill
          auto-update-conda: true

      - name: Set PATH
        run: |
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Basic tests
        run: |
          shovill --version
          shovill --check
          shovill --help
          ! shovill --doesnotexist

      - name: Spades
        run: |
          shovill --outdir out.spades --assembler spades --R1 test/R1.fq.gz --R2 test/R2.fq.gz
          seqkit stats out.spades/contigs.fa

      - name: Plasmid mode
        run: |
          shovill --plasmid --outdir out.spades --assembler spades --R1 test/R1.fq.gz --R2 test/R2.fq.gz --nostitch --noreadcorr --nocorr
          seqkit stats out.spades/contigs.fa

      - name: SKESA
        run: |
          shovill --outdir out.skesa --assembler skesa --R1 test/R1.fq.gz --R2 test/R2.fq.gz --nostitch --nocorr
          seqkit stats out.skesa/contigs.fa

      - name: Megahit
        run: |
          shovill --outdir out.megahit --assembler megahit --R1 test/R1.fq.gz --R2 test/R2.fq.gz --trim
          seqkit stats out.megahit/contigs.fa

      - name: Velvet
        run: |
          shovill --outdir out.velvet --assembler velvet --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 8 --noreadcorr --nocorr
          seqkit stats out.velvet/contigs.fa

